### PR TITLE
MaybeT implemented

### PR DESCRIPTION
**Pull request by mseri**
There is a massive amount of changes overall to use MaybeT and simplify the library.
This branch is compiling and working properly (at least seems so).

To be able to simplify also the app, we might implement a transformer (sort of the inverse of hush in Directives) and use that to present the error messages.

### CODE REVIEW

**Comment by mseri** [comment]
I am working on the merge right now. Please do not push big changes for the next few minutes ;-P

**Comment by mseri** [comment]
Ready for merge :)

**Comment by shtukas** [comment]
I will have a look. By the way, there is something we keep doing differently (we keep reverting each other's changes). The space between "import" and the name of the module is fine (the space is as big as "qualified"), but I am not super fan of aligning the aliases. In other words 

```
import           Data.Aeson as A
```

but not

```
import           Data.Aeson                               as A
```

Unless you feel strongly about it :)

**Comment by mseri** [comment]
I am perfectly fine in not aligning them, but I like them in alphabetical order :)
It was made by I linter, I will look into disabling the option.

**Comment by shtukas** [comment]
Deal!

**Comment by mseri** [comment]
:+1:

**Comment by shtukas** [comment]
I have just corrected a bug ( see 1938b47a4febdfec144a9ab160695f2e8c2589d6 ) and that has created a merge conflict with one of the modifs you made in SearchEngine. I leave it to you 

```
<<<<<<< HEAD
    aionPointAsByteString <- MaybeT $ CAS.get key
    let aesonValue = GAOU.convertJSONStringIntoAesonValue (Char8.unpack aionPointAsByteString)
    returnAppropriateName aesonValue
    where
        returnAppropriateName :: Maybe A.Value -> MaybeT IO String
        returnAppropriateName Nothing = mzero
        returnAppropriateName (Just aesonValue) = let tap = GAOU.aesonValueToTAionPoint aesonValue in return (name1 tap)
=======
    aionPointAsMaybeByteString <- CAS.get key
    case aionPointAsMaybeByteString of
        Nothing                    -> return Nothing
        Just aionPointAsByteString -> do
            let aesonValue = GAOU.convertJSONStringIntoAesonValue (Char8.unpack aionPointAsByteString)
            case aesonValue of
                Nothing          -> return Nothing 
                Just aesonValue' -> do
                    if GAOU.aesonValueIsFile aesonValue'
                        then do
                            let tap = GAOU.aesonValueToTAionPoint aesonValue'
                            return $ Just ( name1 tap )
                        else do
                            let tap = GAOU.aesonValueToTAionPoint aesonValue'
                            return $ Just ( name2 tap )
>>>>>>> master
```

**Comment by mseri** [comment]
I cannot do it now but it's enough to replace

``` haskell
returnAppropriateName (Just aesonValue) = 
    let tap = GAOU.aesonValueToTAionPoint aesonValue in return (name1 tap)
```

with

``` haskell
returnAppropriateName (Just aesonValue) = 
    let tap = GAOU.aesonValueToTAionPoint aesonValue in 
    let name = if GAOU.aesonValueIsFile aesonValue then name1 tap else name2 tap in
    return name
```

**Comment by shtukas** [comment]
Merged (mostly because I want to carry on coding), but I have a warning...

```
src/Gaia/SearchEngine.hs:65:9: Warning:
    Pattern match(es) are non-exhaustive
    In an equation for ‘returnAppropriateName’:
        Patterns not matched: Nothing
```

**Comment by shtukas** [comment]
Corrected!

**Comment by mseri** [comment]
These two lines had to stay

``` haskell
    returnAppropriateName :: Maybe A.Value -> MaybeT IO String
    returnAppropriateName Nothing = mzero
```

**Comment by mseri** [comment]
:P :+1:

**Pull request merged**
